tasks:
  - name: Install, build and run
    init: rush install && rush build
    command: cd blog && rushx start

ports:
  - port: 3000
    onOpen: open-preview
    name: Blog
    description: Blog

github:
  prebuilds:
    addBadge: true

image:
  file: .devcontainer/Dockerfile
