name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blog
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Get pnpm version
        id: pnpmVersion
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'rush.json'
          prop_path: 'pnpmVersion'
      - uses: pnpm/action-setup@v2
        with:
          version: ${{steps.pnpmVersion.outputs.prop}}
      - name: Install Packages
        run: node ../common/scripts/install-run-rush.js install --from git:origin/main
      - name: Build
        run: node ../common/scripts/install-run-rush.js build --from git:origin/main
      - name: Test
        run: node ../common/scripts/install-run-rush.js test --impacted-by git:origin/main
